apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-metallb-system
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/subhakar-ci-cd/metallb-system'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []