apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-nginx-ingress
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: overlays/development
    repoURL: 'https://github.com/subhakar-ci-cd/ingress-nginx-kustomize'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []