apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-prerequisites
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: overlays/development/app-prerequisites
    repoURL: 'https://github.com/subhakar-ci-cd-tools/k8s-argocd-deployment'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
