apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/subhakar-ci-cd/k8s-argocd-deployment
      type: git
    - url: https://github.com/subhakar-ci-cd/metallb-system
      type: git
    - url: https://github.com/subhakar-ci-cd/ingress-nginx-kustomize
      type: git
    - url: https://github.com/subhakar-ci-cd/istio-operator-kustomize
      type: git
    - url: https://github.com/subhakar-ci-cd/helm-charts
      type: git
