apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  #- ../../base
  - github.com/shivakumar12/argocd-base/overlays/development?ref=v2.0.0
resources:
  - app-argocd.yaml
  - app-of-apps.yaml
  - app-of-prerequisites.yaml
patchesStrategicMerge:
  - argocd-server-service.yaml
  - argocd-configmap.yaml
  #- kustomize-upgrade.yaml
